### ISSUE TITLE
Rendering Issues in Dimenions other than the Overworld

### ISSUE THREAD

**Issue by zacklmoore** [AlexIIL/Buildcraft_1.8_Issues#129]
Hello,

I'm using the latest BC Pre-Release (Pre-12) and having some odd rendering issues. Everything seems to function perfectly fine and shows up properly in the overworld, but when I attempt to use any BC stuff in other dimensions (such as the nether) there are quite a few rendering issues including:

Contents of pipes not rendering, the outline of a quarry before it has been built not showing, and the moving arms / mining head of the quarry not rendering.

Let me know if there are any additional details you could use to help solve this issue!

**Comment by AlexIIL** [comment]
Thanks for letting me know- its technically a network problem as if you fill up a tank (in singleplayer) you can see the amount of fluid in the tank (because singlelayer tanks use the integrated server for speed), but if you look at in creative mode + F3 then it shows up as empty.

![screenshot from 2016-03-04 20 10 50](https://cloud.githubusercontent.com/assets/3751138/13538980/6391335a-e245-11e5-81bb-560a1d0f43c1.png)

**Comment by AlexIIL** [comment]
This should be fixed in 7.2.0 proper.
